<?php
/**
 * Game-wise student count report (Excel) for one department.
 *
 * For each game in the department's catalog: Male / Female / Other / Total
 * student counts (submitted profiles only). A student who picked more than
 * one game appears in each game's row, so the game rows don't sum to the
 * "Total Students" figure in the header block — that's a distinct headcount.
 *
 * GET params:
 *   ?department=123  -> required for SUPER_ADMIN; ignored (forced to own
 *                        dept) for FACULTY
 *
 * Output: .xls (SpreadsheetML 2003 XML — opens in Excel, LibreOffice, Google Sheets)
 * No external libraries; pure XML. Mirrors admin/export_xlsx.php.
 */

declare(strict_types=1);

require_once __DIR__ . '/../includes/bootstrap.php';
require_login();
require_department();

$me = current_faculty();

$department_id = $me['role'] === 'FACULTY'
    ? (int)$me['department_id']
    : (int)($_GET['department'] ?? 0);

if ($department_id <= 0) {
    http_response_code(400);
    exit('Select a faculty to generate this report.');
}

$dept = db_one('SELECT id, name FROM departments WHERE id = ? AND is_active = 1', [$department_id], 'i');
if (!$dept) {
    http_response_code(404);
    exit('Faculty not found.');
}

$catalog = load_gamewise_gender_counts($department_id);
if (empty($catalog)) {
    http_response_code(404);
    exit('No games are configured for this faculty yet.');
}
$totals = load_department_gender_totals($department_id);

$college = db_one('SELECT * FROM college_settings WHERE id = 1') ?? [
    'name' => 'YSPM Yashoda Technical Campus',
];
$generated_at = date('d M Y, H:i');
$generated_by = $me['full_name'];

/* ---------------- build XML ---------------- */

function xml_escape($s): string {
    if ($s === null) return '';
    return htmlspecialchars((string)$s, ENT_QUOTES | ENT_XML1, 'UTF-8');
}

function xml_cell($value, $type = 'String', $styleId = null): string {
    $s = $styleId !== null ? ' ss:StyleID="' . $styleId . '"' : '';
    $v = xml_escape($value);
    return "<Cell$s><Data ss:Type=\"$type\">$v</Data></Cell>";
}

$styles = '
<Styles>
  <Style ss:ID="Header">
    <Font ss:Bold="1" ss:Color="#FFFFFF"/>
    <Interior ss:Color="#1A365D" ss:Pattern="Solid"/>
    <Alignment ss:Horizontal="Center" ss:Vertical="Center" ss:WrapText="1"/>
    <Borders>
      <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
      <Border ss:Position="Top"    ss:LineStyle="Continuous" ss:Weight="1"/>
      <Border ss:Position="Left"   ss:LineStyle="Continuous" ss:Weight="1"/>
      <Border ss:Position="Right"  ss:LineStyle="Continuous" ss:Weight="1"/>
    </Borders>
  </Style>
  <Style ss:ID="Data">
    <Alignment ss:Vertical="Top" ss:WrapText="1"/>
    <Borders>
      <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="0.5"/>
      <Border ss:Position="Left"   ss:LineStyle="Continuous" ss:Weight="0.5"/>
      <Border ss:Position="Right"  ss:LineStyle="Continuous" ss:Weight="0.5"/>
    </Borders>
  </Style>
  <Style ss:ID="Total">
    <Font ss:Bold="1"/>
    <Alignment ss:Vertical="Top"/>
    <Interior ss:Color="#F1F5F9" ss:Pattern="Solid"/>
    <Borders>
      <Border ss:Position="Top"    ss:LineStyle="Continuous" ss:Weight="1"/>
      <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
      <Border ss:Position="Left"   ss:LineStyle="Continuous" ss:Weight="0.5"/>
      <Border ss:Position="Right"  ss:LineStyle="Continuous" ss:Weight="0.5"/>
    </Borders>
  </Style>
  <Style ss:ID="Label">
    <Font ss:Bold="1"/>
    <Alignment ss:Horizontal="Right" ss:Vertical="Top"/>
  </Style>
  <Style ss:ID="Note">
    <Font ss:Italic="1" ss:Color="#6c757d" ss:Size="9"/>
    <Alignment ss:Vertical="Top" ss:WrapText="1"/>
  </Style>
</Styles>';

// Header block rows (label : value)
$header_rows = [
    ['College',        $college['name']],
    ['Faculty',        $dept['name']],
    ['Generated On',   $generated_at],
    ['Generated By',   $generated_by],
    ['Total Students', $totals['total']],
    ['Male Students',  $totals['male']],
    ['Female Students', $totals['female']],
];
if ($totals['other'] > 0) {
    $header_rows[] = ['Other / Not Specified', $totals['other']];
}
$header_block = '';
foreach ($header_rows as $hr) {
    $header_block .= '<Row>'
        . xml_cell($hr[0], 'String', 'Label')
        . xml_cell($hr[1], is_int($hr[1]) ? 'Number' : 'String')
        . '</Row>';
}
$header_block .= '<Row></Row>';

$note_row = '<Row><Cell ss:StyleID="Note" ss:MergeAcross="4"><Data ss:Type="String">'
    . xml_escape('A student who picked more than one game appears in each game\'s row below, so the game rows do not sum to "Total Students" above.')
    . '</Data></Cell></Row><Row></Row>';

// Column headers
$has_other = $totals['other'] > 0;
$columns = ['Game', 'Male', 'Female'];
if ($has_other) $columns[] = 'Other';
$columns[] = 'Total';
$col_header_row = '<Row ss:Height="26">';
foreach ($columns as $col) {
    $col_header_row .= xml_cell($col, 'String', 'Header');
}
$col_header_row .= '</Row>';

// Data rows
$data_rows = '';
$sum_male = $sum_female = $sum_other = $sum_total = 0;
foreach ($catalog as $g) {
    $data_rows .= '<Row>';
    $data_rows .= xml_cell($g['display_name'], 'String', 'Data');
    $data_rows .= xml_cell($g['male'],   'Number', 'Data');
    $data_rows .= xml_cell($g['female'], 'Number', 'Data');
    if ($has_other) $data_rows .= xml_cell($g['other'], 'Number', 'Data');
    $data_rows .= xml_cell($g['total'],  'Number', 'Data');
    $data_rows .= '</Row>';
    $sum_male   += $g['male'];
    $sum_female += $g['female'];
    $sum_other  += $g['other'];
    $sum_total  += $g['total'];
}
$data_rows .= '<Row>' . xml_cell('Total Game Selections', 'String', 'Total')
    . xml_cell($sum_male,   'Number', 'Total')
    . xml_cell($sum_female, 'Number', 'Total');
if ($has_other) $data_rows .= xml_cell($sum_other, 'Number', 'Total');
$data_rows .= xml_cell($sum_total, 'Number', 'Total') . '</Row>';

// Column widths
$widths = [200, 70, 70];
if ($has_other) $widths[] = 70;
$widths[] = 70;
$cols_xml = '';
foreach ($widths as $i => $w) {
    $cols_xml .= '<Column ss:Index="' . ($i + 1) . '" ss:Width="' . $w . '"/>';
}

$xml = '<?xml version="1.0" encoding="UTF-8"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">
' . $styles . '
<Worksheet ss:Name="Game-wise Count">
<Table>
' . $cols_xml . $header_block . $note_row . $col_header_row . $data_rows . '
</Table>
</Worksheet>
</Workbook>';

/* ---------------- send headers ---------------- */

$filename = 'gamewise_report_' . preg_replace('/[^A-Za-z0-9_-]/', '_', $dept['name']) . '_' . date('Ymd') . '.xls';

header('Content-Type: application/vnd.ms-excel; charset=utf-8');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('Pragma: no-cache');

// BOM so Excel opens UTF-8 correctly
echo "\xEF\xBB\xBF" . $xml;
