<?php
/**
 * Excel export for a provisional player list.
 *
 * GET params:
 *   game    string  the game name (required)
 *   event   string  the event label (required)
 *   ay      string  the academic year (optional)
 *   gender  string  "Male" or "Female" (optional — omit to export the
 *                    legacy, un-gendered rows only)
 *
 * Output: .xls (SpreadsheetML 2003 XML — opens in Excel, LibreOffice, Google Sheets)
 * No external libraries; pure XML.
 */

declare(strict_types=1);

require_once __DIR__ . '/../includes/bootstrap.php';
require_login();
require_department();

$me     = current_faculty();
$game   = trim((string)($_GET['game'] ?? ''));
// Provisional lists use a fixed sentinel event label (see provisional_list.php).
$event  = trim((string)($_GET['event'] ?? ''));
if ($event === '') $event = 'Provisional';
$is_sentinel_event = ($event === 'Provisional');
$ay     = trim((string)($_GET['ay'] ?? ''));
$gender = trim((string)($_GET['gender'] ?? ''));
if (!array_key_exists($gender, gender_list_options())) $gender = '';

if ($game === '') {
    http_response_code(400);
    exit('Game is required.');
}

/* ---------------- load scope data ---------------- */

$college = db_one('SELECT * FROM college_settings WHERE id = 1') ?? [
    'name'    => 'YSPM Yashoda Technical Campus',
    'address' => '',
];

[$scope, $p, $t] = scope_sql_department('s');
// Hide wizard drafts (students who registered but haven't hit Final Submit).
$visible = faculty_visible_student_filter('s');
$scope  .= $visible[0];
$p       = array_merge($p, $visible[1]);
$t      .= $visible[2];

$rows = db_select(
    "SELECT pe.id AS entry_id, pe.created_at AS added_at,
            s.id, s.enrollment_no, s.full_name,
            s.gender, s.dob, s.email, s.mobile, s.whatsapp_no,
            s.program, s.study_year, s.has_played_in_college,
            s.zonal_played, s.zonal_year, s.interzonal_played, s.interzonal_year,
            s.all_india_played, s.all_india_year,
            s.west_zone_played, s.west_zone_year,
            s.krida_mahotsav_played, s.krida_mahotsav_year,
            d.name AS dept_name
       FROM provisional_entries pe
       JOIN students s    ON s.id = pe.student_id
       JOIN departments d ON d.id = s.department_id
      WHERE pe.game_name = ?
        AND pe.event_label = ?
        AND pe.academic_year <=> ?
        AND pe.gender <=> ?
        $scope
      ORDER BY pe.created_at ASC, s.enrollment_no ASC",
    array_merge([$game, $event, $ay === '' ? null : $ay, $gender === '' ? null : $gender], $p), 'ssss' . $t
);

if (!$rows) {
    http_response_code(404);
    exit('No players found for this list.');
}

$dept_label   = $me['department_name'] ?? 'All Faculties';
$generated_at = date('d M Y, H:i');
$generated_by = $me['full_name'];
$total        = count($rows);

/* ---------------- build XML ---------------- */

function xml_escape_prov($s): string {
    if ($s === null) return '';
    return htmlspecialchars((string)$s, ENT_QUOTES | ENT_XML1, 'UTF-8');
}

function xml_cell_prov($value, $type = 'String', $styleId = null): string {
    $s = $styleId !== null ? ' ss:StyleID="' . $styleId . '"' : '';
    $v = xml_escape_prov($value);
    return "<Cell$s><Data ss:Type=\"$type\">$v</Data></Cell>";
}

$styles = '
<Styles>
  <Style ss:ID="Title">
    <Font ss:Bold="1" ss:Size="14"/>
    <Alignment ss:Horizontal="Left" ss:Vertical="Center"/>
  </Style>
  <Style ss:ID="Header">
    <Font ss:Bold="1" ss:Color="#FFFFFF"/>
    <Interior ss:Color="#1A365D" ss:Pattern="Solid"/>
    <Alignment ss:Horizontal="Center" ss:Vertical="Center" ss:WrapText="1"/>
    <Borders>
      <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
      <Border ss:Position="Top"    ss:LineStyle="Continuous" ss:Weight="1"/>
      <Border ss:Position="Left"   ss:LineStyle="Continuous" ss:Weight="1"/>
      <Border ss:Position="Right"  ss:LineStyle="Continuous" ss:Weight="1"/>
    </Borders>
  </Style>
  <Style ss:ID="Data">
    <Alignment ss:Vertical="Top" ss:WrapText="1"/>
    <Borders>
      <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="0.5"/>
      <Border ss:Position="Left"   ss:LineStyle="Continuous" ss:Weight="0.5"/>
      <Border ss:Position="Right"  ss:LineStyle="Continuous" ss:Weight="0.5"/>
    </Borders>
  </Style>
  <Style ss:ID="Label">
    <Font ss:Bold="1"/>
    <Alignment ss:Horizontal="Right" ss:Vertical="Top"/>
  </Style>
</Styles>';

// Header block rows
$header_rows = [
    ['College',        $college['name']],
    ['Faculty',        $dept_label],
    ['Game / Sport',   $game],
];
if (!$is_sentinel_event) {
    $header_rows[] = ['Event', $event];
}
$header_rows = array_merge($header_rows, [
    ['Academic Year',  $ay !== '' ? $ay : 'Any'],
    ['Gender',         gender_list_options()[$gender] ?? 'Unspecified'],
    ['Generated On',   $generated_at],
    ['Generated By',   $generated_by],
    ['Total Players',  $total],
]);
$header_block = '';
foreach ($header_rows as $hr) {
    $header_block .= '<Row>'
        . xml_cell_prov($hr[0], 'String', 'Label')
        . xml_cell_prov($hr[1], 'String')
        . '</Row>';
}

// Blank spacer row
$header_block .= '<Row></Row>';

// Column headers
$columns = [
    'Sr. No.', 'Enrollment No.', 'Full Name', 'Gender', 'Date of Birth',
    'Email', 'Mobile', 'WhatsApp No.', 'Program / Branch', 'Faculty',
    'Year of Study', 'Playing History',
];
$col_header_row = '<Row ss:Height="30">';
foreach ($columns as $col) {
    $col_header_row .= xml_cell_prov($col, 'String', 'Header');
}
$col_header_row .= '</Row>';

// Data rows
$data_rows = '';
$sr = 1;
foreach ($rows as $r) {
    $dob = !empty($r['dob']) ? date('d-m-Y', strtotime($r['dob'])) : '';

    // "Playing History" — the tournament levels the student has actually
    // participated in (with year, when known). "No" when there is none.
    $played_bits = [];
    foreach (participation_levels() as $lvl) {
        if ((int)($r[$lvl['played_col']] ?? 0) === 1) {
            $yr = trim((string)($r[$lvl['year_col']] ?? ''));
            $played_bits[] = $lvl['label'] . ($yr !== '' ? " ($yr)" : '');
        }
    }
    if ($played_bits) {
        $history = 'Yes — ' . implode(', ', $played_bits);
    } elseif ((int)($r['has_played_in_college'] ?? 0) === 1) {
        $history = 'Yes';
    } else {
        $history = 'No';
    }

    $data_rows .= '<Row>';
    $data_rows .= xml_cell_prov($sr++, 'Number', 'Data');
    $data_rows .= xml_cell_prov($r['enrollment_no'],  'String', 'Data');
    $data_rows .= xml_cell_prov($r['full_name'],      'String', 'Data');
    $data_rows .= xml_cell_prov($r['gender'] ?? '',   'String', 'Data');
    $data_rows .= xml_cell_prov($dob,                 'String', 'Data');
    $data_rows .= xml_cell_prov($r['email'] ?? '',    'String', 'Data');
    $data_rows .= xml_cell_prov($r['mobile'] ?? '',   'String', 'Data');
    $data_rows .= xml_cell_prov($r['whatsapp_no'] ?? '', 'String', 'Data');
    $data_rows .= xml_cell_prov($r['program'] ?? '',  'String', 'Data');
    $data_rows .= xml_cell_prov($r['dept_name'],      'String', 'Data');
    $data_rows .= xml_cell_prov($r['study_year'] ?? '', 'String', 'Data');
    $data_rows .= xml_cell_prov($history,             'String', 'Data');
    $data_rows .= '</Row>';
}

// Column widths
$widths = [55, 120, 190, 70, 100, 200, 110, 110, 190, 150, 100, 260];
$cols_xml = '';
foreach ($widths as $i => $w) {
    $cols_xml .= '<Column ss:Index="' . ($i + 1) . '" ss:Width="' . $w . '"/>';
}

$sheet_name = mb_substr("Provisional - $game", 0, 31); // Excel max sheet name = 31 chars

$xml = '<?xml version="1.0" encoding="UTF-8"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">
' . $styles . '
<Worksheet ss:Name="' . xml_escape_prov($sheet_name) . '">
<Table>
' . $cols_xml . $header_block . $col_header_row . $data_rows . '
</Table>
</Worksheet>
</Workbook>';

/* ---------------- send headers ---------------- */

$safe_game   = preg_replace('/[^A-Za-z0-9_-]/', '_', $game);
$safe_event  = $is_sentinel_event ? '' : preg_replace('/[^A-Za-z0-9_-]/', '_', $event);
$safe_gender = gender_list_options()[$gender] ?? '';
$filename    = 'provisional_' . $safe_game
    . ($safe_event !== '' ? '_' . $safe_event : '')
    . ($safe_gender !== '' ? '_' . $safe_gender : '') . '_' . date('Ymd') . '.xls';

header('Content-Type: application/vnd.ms-excel; charset=utf-8');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('Pragma: no-cache');

// BOM so Excel opens UTF-8 correctly
echo "\xEF\xBB\xBF" . $xml;
